include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  exclude:
    - test/old

linter:
  rules:
    sort_pub_dependencies: true
    prefer_relative_imports: true
    prefer_single_quotes: true