builders:
  stormberry:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "buildSchema" ]
    build_extensions: { ".dart": [ ".schema.g.dart", ".schema.g.json" ] }
    auto_apply: none
    build_to: source