name: stormberry
description: Access your postgres database effortlessly from dart code.
version: 0.9.0
repository: https://github.com/schultek/stormberry
issue_tracker: https://github.com/schultek/stormberry/issues

dependencies:
  analyzer: ">=4.2.0 <5.0.0"
  args: ^2.3.1
  build: ^2.3.1
  collection: ^1.16.0
  crypto: ^3.0.2
  dart_style: ^2.2.4
  path: ^1.8.2
  postgres: ^2.5.1
  source_gen: ^1.2.3
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
  test: ^1.21.0

environment:
  sdk: '>=2.16.0 <3.0.0'
