name: dartabase
description: Manage your database schema from dart code.
version: 0.1.0
repository: https://github.com/schultek/dartabase
issue_tracker: https://github.com/schultek/dartabase/issues

dependencies:
  analyzer: ^1.4.0
  build: ^2.0.0
  postgres: ^2.3.1
  source_gen: ^1.0.0

dev_dependencies:
  lint: ^1.5.3

environment:
  sdk: '>=2.12.0 <3.0.0'
