name: stormberry
description: Access your postgres database effortlessly from dart code.
version: 0.7.0
repository: https://github.com/schultek/stormberry
issue_tracker: https://github.com/schultek/stormberry/issues

dependencies:
  analyzer: ^3.3.1
  build: ^2.2.1
  collection: ^1.16.0
  crypto: ^3.0.1
  dart_style: ^2.2.2
  path: ^1.8.2
  postgres: ^2.4.3
  source_gen: ^1.2.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1

environment:
  sdk: '>=2.12.0 <3.0.0'
